src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['username'], message: 'There is already an account with this username')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $username = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    private ?string $Prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255)]
    private ?string $ville = null;

    #[ORM\Column]
    private ?int $CP = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $dateAt = null;

    #[ORM\OneToMany(mappedBy: 'User', targetEntity: Order::class)]
    private Collection $orders;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCP(): ?int
    {
        return $this->CP;
    }

    public function setCP(int $CP): self
    {
        $this->CP = $CP;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getDateAt(): ?\DateTimeImmutable
    {
        return $this->dateAt;
    }

    public function setDateAt(\DateTimeImmutable $dateAt): self
    {
        $this->dateAt = $dateAt;

        return $this;
    }

    /**
     * @return Collection<int, Order>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders->add($order);
            $order->setUser($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getUser() === $this) {
                $order->setUser(null);
            }
        }

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>{% block title %} MÉTÉORE {% endblock %}</title>
    <link rel="stylesheet" href="{{ asset('css/bootstrap.css') }}"/>
    <link rel="stylesheet" href="{{ asset('css/navbar.css') }}"/>
    <link rel="stylesheet" href="{{ asset('css/home.css') }}"/>
    <link rel="stylesheet" href="{{ asset('css/style.css') }}"/>
    {% block css %}{% endblock %}
    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
    <link
            href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&family=Roboto+Flex:opsz,wght@8..144,100;8..144,300;8..144,500;8..144,700;8..144,900&display=swap"
            rel="stylesheet"
    />

</head>
<body>
<header>
    {% block nav %}


        <nav>
            <a href="#" class="nav-icon" aria-label="visit homepage" aria-current="page">
                <img src="{{ asset('ressources/logo.JPG') }}" alt="chat icon">
                <!--<span>EverChat</span> -->
            </a>

            <div class="main-navlinks">
                <button class="hamburger" type="button" aria-label="Toggle navigation" aria-expanded="false">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
                <div class="navlinks-container">
                    <a href="{{ path('home') }}" style="color: #F8760EBF ">HOME</a>
                    <a href="{{ path('info') }}" style="color: white;">ABOUT US</a>
                    <div class="drop">
                        <a href="{{ path('casque') }}">SHOP</a>
                        <div class="content">
                            <a href="{{ path('casque') }}">CASQUES</a>
                            <a href="{{ path('acc') }}">ACCESSOIRES</a>
                            <a href="{{ path('epauliere') }}">ÉPAULIÈRES</a>
                            <a href={{ path('crampons') }}>CRAMPONS</a>
                        </div>
                    </div>
                    <form class="d-flex" action="{{ path('panier') }}" method="POST">
                        <button class="btn btn-light" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                        </button>
                    </form>
                </div>
            </div>
            <div class="nav-authentication">
                <a href="{{ path('profil') }}" class="sign-user" aria-label="Sign in page">
                    <img src="{{ asset('ressources/user.svg') }}" alt="user-icon">
                </a>
                {% if is_granted('IS_AUTHENTICATED_FULLY') %}

                    <div class="sign-btns">
                        <a href="{{ path('profil') }}" class="btn btn-close-white"><i class=" bx bxs-user"></i>
                            {{ app.user.nom }}</a>
                        <a href="{{ path('app_logout') }}" class="btn btn-danger">DÉCONNEXION</a>


                        {% if is_granted('ROLE_ADMIN') %}
                            <a href="{{ path('admin') }}" class="btn btn-info">ADMIN</a>
                        {% endif %}

                    </div>
                {% else %}
                    <div class="sign-btns">
                        <button id="Connexion" type="button">CONNEXION</button>

                        <button id="Inscription" type="button">INSCRIPTION</button>
                    </div>
                {% endif %}
            </div>
        </nav>
    {% endblock %}
</header>

<main>
    {% block main %} {% endblock %}
</main>
{% block footer %}
<footer class="footer">
    <aside class="us">
        <p>Contact US </p>
        <p>01 01 01 01 01</p>
        <p>météore@admin.fr</p>
        <p>9 rue de Rosny, Fontenay-sous-bois, 94120</p>
    </aside>

    <aside class="mentions">
    <a href="#">&copy; Météore de Fontenay</a>
    <a href="{{ asset('img/mentions/Votre-document.jpg') }}" target="_blank">Mentions Légale</a>
    <a href="{{ asset('img/mentions/CGU.jpg') }}" target="_blank">CGU</a>
    <a href="{{ asset('img/mentions/CGU.jpg') }}" target="_blank">CGV</a>
    </aside>

</footer>

{% endblock %}
<script src="{{ asset('js/script.js') }}"></script>
<script src="{{ asset('js/bootstrap.js') }}"></script>
<script>
    document.getElementById("Connexion").onclick = function () {
        location.href = "{{ path('connexion') }}";
    };

    document.getElementById("Inscription").onclick = function () {
        location.href = "{{ path('inscription') }}";
    };

    document.getElementById("déco").onclick = function () {
        location.href = "{{ path('app_logout') }}";
    };

    document.getElementById("admin").onclick = function () {
        location.href = "{{ path('admin') }}";
    };
</script>
{% block js %}{% endblock %}
</body>
</html>